resources:
  repositories:
    - repository: coretemplate
      type: git
      name: WizPipelines/core-template

extends:
  template: main.yml@coretemplate
  parameters:
    technology: "dotnetcore"
    deploymentType: "webapp"
    dotnetcoreAppType: "functionApp"
    azWebAppNameUAT: "template-hml-fn"
    azWebAppNamePRD: "template-prd-fn"
    azResourceName: "templateresource"
    azSubscriptionUAT: "AmbientesDevHml"
    azSubscriptionPRD: "AmbienteCorporativoExterior"    
    dotnetcoreDotNetVersion: "8.x"
    dotnetcoreBuildProject: "**/Wiz.Template.Function.csproj"
    dotnetcoreBuildConfiguration: Release
    appSettingsUAT:
      -Connection "<SERVICEBUS-CONNECTIONSTRING>"
      -Topic "<SERVICEBUS-TOPIC>"
      -Subscription "<SERVICEBUS-SUBSCRIPTION>"
      -FUNCTIONS_WORKER_RUNTIME "dotnet-isolated"
      -AZURE_FUNCTIONS_ENVIRONMENT "Staging"
      -APPLICATIONINSIGHTS_CONNECTION_STRING "<APPINSIGHTS-CONNECTIONSTRING>"
      -ConnectionStrings:AppConfig "<APPCONFIG-CONNECTIONSTRING>"
      -AppConfiguration:Prefix "WPRO:Template:*"
      -AppConfiguration:Sentinel "WPRO:Template:Sentinel"
      -AppConfiguration:CacheExpirationFromMinutes "15"
      -LogAnalyticsSettings:SharedKey "<LOGANALYTICS-SHAREDKEY>"
      -LogAnalyticsSettings:WorkspaceId "<LOGANALYTICS-WORKSPACEID>"
      -LogAnalyticsSettings:ApiVersion "2016-04-01"
      -LogAnalyticsSettings:BaseUrlPattern "https://{0}.ods.opinsights.azure.com/api/logs?api-version={1}"
      -LogAnalyticsSettings:ContentType "application/json"    
    appSettingsPRD:
      -Connection "<SERVICEBUS-CONNECTIONSTRING>"
      -Topic "<SERVICEBUS-TOPIC>"
      -Subscription "<SERVICEBUS-SUBSCRIPTION>"
      -FUNCTIONS_WORKER_RUNTIME "dotnet-isolated"
      -AZURE_FUNCTIONS_ENVIRONMENT "Staging"
      -APPLICATIONINSIGHTS_CONNECTION_STRING "<APPINSIGHTS-CONNECTIONSTRING>"
      -ConnectionStrings:AppConfig "<APPCONFIG-CONNECTIONSTRING>"
      -AppConfiguration:Prefix "WPRO:Template:*"
      -AppConfiguration:Sentinel "WPRO:Template:Sentinel"
      -AppConfiguration:CacheExpirationFromMinutes "15"
      -LogAnalyticsSettings:SharedKey "<LOGANALYTICS-SHAREDKEY>"
      -LogAnalyticsSettings:WorkspaceId "<LOGANALYTICS-WORKSPACEID>"
      -LogAnalyticsSettings:ApiVersion "2016-04-01"
      -LogAnalyticsSettings:BaseUrlPattern "https://{0}.ods.opinsights.azure.com/api/logs?api-version={1}"
      -LogAnalyticsSettings:ContentType "application/json"    